<?php

namespace AppBundle\Repository;

/**
 * ownerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ownerRepository extends \Doctrine\ORM\EntityRepository
{
}
