<?php

namespace AppBundle\Repository;

/**
 * petRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class petRepository extends \Doctrine\ORM\EntityRepository
{
}
