# app/config/routing.yml
login:
    path: /login
    defaults:
        _controller: AppBundle:Auth:login

signup:
    path: /signup
    controller: AppBundle\Controller\AuthController::signupAction

authenticate:
    path: /authenticate
    defaults:
        _controller: AppBundle:Auth:authenticate
        _method: POST

register:
    path: /register
    defaults:
        _controller: AppBundle:Auth:register
        _method: POST

welcome:
    path: /welcome
    defaults:
        _controller: AppBundle:Auth:welcome
homepage:
    path: /
    defaults:
        _controller: AppBundle:Auth:index

logout:
    path: /logout
    defaults:
        _controller: AppBundle:Auth:logout
add_pet:
    path: /add-pet
    methods: [POST]
    controller: AppBundle\Controller\AuthController::addPet

add_owner:
    path: /add-owner
    methods: [POST]
    controller: AppBundle\Controller\AuthController::addOwner

deletePet:
    path: /deletePet/{id}
    methods: [POST]
    controller: AppBundle\Controller\AuthController::deletePet

updatePet:
    path: '/updatePet/{id}'
    controller: 'AppBundle\Controller\AuthController::updatePet'
    methods: [POST,PUT]

